### PR TITLE
add plugin,theme and Open Source

### PR DESCRIPTION
**Pull request by JoeyBling**

### CODE REVIEW

**Comment by JoeyBling** [comment]
[vuepress-theme-yilia-plus](https://github.com/JoeyBling/vuepress-theme-yilia-plus) theme inherits the official default theme,
plugin and theme demo I will update it in the next few days [https://zhousiwei.gitee.io/ibooks/](https://zhousiwei.gitee.io/ibooks/)

**Comment by JoeyBling** [comment]
如果确实不好弄的话，等我晚点把Demo更新上去了你再通过这个PR也行

**Comment by JoeyBling** [comment]
@ulivz ok啦，我已经把Demo放上去了

**Comment by JoeyBling** [comment]
> Demo url:[https://zhousiwei.gitee.io/ibooks/](https://zhousiwei.gitee.io/ibooks/)

**Comment by ulivz** [comment]
Isn't it your own notes site?

**Pull request closed without merging**
