### PR TITLE
feat: add vuepress-plugin-lastest-version

### PR DESCRIPTION
**Pull request by yangyang0507**
Add vuepress-plugin-lastest-version into awesome vuepress.

### CODE REVIEW

**Review by billyyyyy3320 — COMMENTED** [review]
Could you provide a demo?

**Comment by yangyang0507** [comment]
Demo: https://github.com/baomidou/mybatis-plus-doc

**Comment by yangyang0507** [comment]
config
```js
  plugins: [
    [
      "lastest-version",
      {
        type: "maven",
        repo: "com.baomidou/mybatis-plus"
      }
    ]
  ]
```

effect
replace all 'latest-version' words to real lastest version of artifact

**Review by billyyyyy3320 — APPROVED** [review]

**Comment by billyyyyy3320** [comment]
It'll scan all the content to find `lastest-version`, right?

If that be so, I'd suggest you wrap it by a component. You can type `<LastestVersion>` instead of `lastest-verstion`. With it, you don't need to scan all the content. Or maybe [Define](https://vuepress.vuejs.org/plugin/option-api.html#define) can help you, e.g. `{{ lastest-version }}

**Comment by yangyang0507** [comment]
Thanks, I will consider your advice

**Pull request merged**
